from datetime import datetime
from sqlalchemy import String,Integer,DateTime,Boolean,ForeignKey,Text,Float
from sqlalchemy.orm import Mapped,mapped_column
from .database import Base
class User(Base):
    __tablename__='users'; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(120)); email:Mapped[str]=mapped_column(String(255),unique=True,index=True); password_hash:Mapped[str]=mapped_column(String(255)); role:Mapped[str]=mapped_column(String(30),default='applicant'); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class BusinessProfile(Base):
    __tablename__='business_profiles'; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id')); name:Mapped[str]=mapped_column(String(180)); sector:Mapped[str]=mapped_column(String(80)); location:Mapped[str]=mapped_column(String(100)); project_size:Mapped[str]=mapped_column(String(30)); stage:Mapped[str]=mapped_column(String(50)); employees:Mapped[int]=mapped_column(Integer,default=20); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class Approval(Base):
    __tablename__='approvals'; id:Mapped[int]=mapped_column(primary_key=True); code:Mapped[str]=mapped_column(String(50),unique=True); name:Mapped[str]=mapped_column(String(180)); authority:Mapped[str]=mapped_column(String(180)); sector:Mapped[str]=mapped_column(String(80)); location:Mapped[str]=mapped_column(String(100)); min_size:Mapped[str]=mapped_column(String(30),default='Any'); stages:Mapped[str]=mapped_column(Text); sla_days:Mapped[int]=mapped_column(Integer); sequence:Mapped[int]=mapped_column(Integer); documents:Mapped[str]=mapped_column(Text); description:Mapped[str]=mapped_column(Text)
class Application(Base):
    __tablename__='applications'; id:Mapped[int]=mapped_column(primary_key=True); reference:Mapped[str]=mapped_column(String(40),unique=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id')); approval_id:Mapped[int]=mapped_column(ForeignKey('approvals.id')); status:Mapped[str]=mapped_column(String(40),default='Draft'); submitted_at:Mapped[datetime|None]=mapped_column(DateTime,nullable=True); due_at:Mapped[datetime|None]=mapped_column(DateTime,nullable=True); query:Mapped[str|None]=mapped_column(Text,nullable=True); department:Mapped[str]=mapped_column(String(120),default='Department Review'); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class Document(Base):
    __tablename__='documents'; id:Mapped[int]=mapped_column(primary_key=True); application_id:Mapped[int]=mapped_column(ForeignKey('applications.id')); original_name:Mapped[str]=mapped_column(String(255)); stored_name:Mapped[str]=mapped_column(String(255)); mime_type:Mapped[str]=mapped_column(String(120)); size_bytes:Mapped[int]=mapped_column(Integer); status:Mapped[str]=mapped_column(String(40),default='Uploaded'); validation_score:Mapped[float]=mapped_column(Float,default=0); validation_notes:Mapped[str]=mapped_column(Text,default='Pending validation'); uploaded_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class WorkflowStep(Base):
    __tablename__='workflow_steps'; id:Mapped[int]=mapped_column(primary_key=True); application_id:Mapped[int]=mapped_column(ForeignKey('applications.id')); step_name:Mapped[str]=mapped_column(String(120)); department:Mapped[str]=mapped_column(String(120)); status:Mapped[str]=mapped_column(String(40),default='Pending'); started_at:Mapped[datetime|None]=mapped_column(DateTime,nullable=True); completed_at:Mapped[datetime|None]=mapped_column(DateTime,nullable=True); sequence:Mapped[int]=mapped_column(Integer)
class Incentive(Base):
    __tablename__='incentives'; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(180)); sector:Mapped[str]=mapped_column(String(80)); state:Mapped[str]=mapped_column(String(80)); benefit:Mapped[str]=mapped_column(String(255)); eligibility:Mapped[str]=mapped_column(Text)
class Renewal(Base):
    __tablename__='renewals'; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id')); title:Mapped[str]=mapped_column(String(180)); due_date:Mapped[datetime]=mapped_column(DateTime); status:Mapped[str]=mapped_column(String(30),default='Upcoming')
